leafmap/common.py, tests/test_foliumap.py, tests/test_leafmap.py
The user may want to connect to a db on a port other than 5432. This PR exposes an optional `port` parameter when creating the engine/connection string.
=> add optional postgis port param

docs/notebooks/22_time_slider.ipynb
This PR adds an example to the time slider notebook, which queries a STAC API (https://earth-search.aws.element84.com/v0) for STAC items, containing COG assets, and assembles the results into a time slider.
=> add STAC time slider example to notebook

docs/installation.md, docs/notebooks/32_local_tile.ipynb, examples/notebooks/32_local_tile.ipynb, leafmap/common.py, leafmap/foliumap.py, leafmap/leafmap.py, mkdocs.yml
Built upon the amazing [localtileserver](https://github.com/banesullivan/localtileserver) package by @banesullivan, leafmap now supports loading local raster dataset and remote Cloud Optimized GeoTIFF (COG) with only one line of code. 
It supports both the ipyleaflet and folium plotting backends. Use either `import leafmap` or `import leafmap.foliumap as leafmap`. The remaining code stays the same. 
**Add a local raster dataset**
```python
import leafmap
m.add_local_tile('dem.tif', palette='matplotlib.Viridis_10', layer_name="DEM")
m
```
**Add a remote COG**
```python
import leafmap
url = 'https://opendata.digitalglobe.com/events/california-fire-2020/pre-event/2018-02-16/pine-gulch-fire20/1030010076004E00.tif'
m.add_remote_tile(url, layer_name="CA …
```
=> Add support for local raster datasets and remote COGs using localtileserver 

CITATION.cff
Hi @giswqs,
It seems that there is a copy'n'paste issue with your `CITATION.cff` file, as releases for leafmap are pushed to my ORCID account. Presumably the ORCID id wasn't changed, but left in from a copied example?
- The releases of this software show up under my ORCID profile, which is wrong as I'm not an author of this leafmap
- Removing the ORCID line also doesn't auto-push any new releases on Zenodo to ORCID
- Ideally, put in the relevant correct ORCID instead
- This PR replaces my id with the one taken from the JOSS paper
=> Replace ORCID in CITATION.cff

docs/notebooks/32_local_tile.ipynb, docs/notebooks/43_search_control.ipynb, examples/notebooks/32_local_tile.ipynb, examples/notebooks/43_search_control.ipynb, leafmap/leafmap.py, leafmap/toolbar.py
Per [Nominatim Usage Policy](https://operations.osmfoundation.org/policies/nominatim), leafmap can't have the Nominatim URL hard coded in the package. Users can choose to add a search control by specifying a URL.  @martinRenou @martinfleis
```python
url = "https://nominatim.openstreetmap.org/search?format=json&q={s}"
m.add_search_control(url)
m
```
=> Removed nominatim URL from Search Control

leafmap/leafmap.py, tests/test_leafmap.py
@giswqs This PR adds fit_bounds support for fit_bounds keyword argument in `leafmap.add_raster` as per #186  -- note: testing is limited to ensuring that `add_raster` still works with fit_bounds=True, False, or not present.  Of course let me know if you want additional tests and/or can suggest a strategy for such tests.
=> Support fit_bounds in leafmap.add_raster

leafmap/basemaps.py, leafmap/foliumap.py, leafmap/leafmap.py, tests/test_foliumap.py, tests/test_leafmap.py
`getattr` is more robust and cleaner than trying to use eval for getting parameters
=> Use getattr instead of eval

leafmap/common.py, leafmap/leafmap.py, requirements.txt
Built upon [mapclassify](https://pysal.org/mapclassify/), this PR adds support for creating choropleth maps with a variety of classification schemes with only one line of code. 
```python
allowed_schemes = [
"BoxPlot",
"EqualInterval",
"FisherJenks",
"FisherJenksSampled",
"HeadTailBreaks",
"JenksCaspall",
"JenksCaspallForced",
"JenksCaspallSampled",
"MaxP",
"MaximumBreaks",
"NaturalBreaks",
"Quantiles",
"Percentiles",
"StdMean",
"UserDefined",
]
```
=> Added support for creating choropleth maps

leafmap/common.py, requirements.txt, requirements_dev.txt
This PR makes mapclassify optional to reduce the size of installed packages for leafmap.
=> Made mapclassify optional

leafmap/leafmap.py, leafmap/toolbar.py, requirements.txt
Thanks to ipyleaflet v0.17.0, leafmap now supports changing GeoJSON layer visibility and opacity interactively. 
@davidbrochart @martinRenou @jasongrout
```python
import leafmap
m.add_basemap("CartoDB.DarkMatter")
in_geojson = 'https://raw.githubusercontent.com/giswqs/geemap/master/examples/data/cable-geo.geojson'
callback = lambda feat: {"color": "#" + feat["properties"]["color"], "weight": 2}
m.add_geojson(in_geojson, layer_name="Cable lines", style_callback=callback, info_mode=None)
m
```
=> Added support for changing geojson layer opacity

leafmap/foliumap.py, leafmap/leafmap.py, tests/test_leafmap.py
- Use consistent parameter names, "layer_name" rather than `name`
- Improve add data methods, accepting HTTP URL as input, such as `add_shp()`, `add_kml()`, `add_geojson`
=> Parameter names and add data methods

leafmap/common.py
This PR adds two functions: `download_ned_by_huc()` and `download_ned_by_bbox()`. #287
=> Added download ned by huc and bbox #287

examples/notebooks/57_the_national_map.ipynb.ipynb, leafmap/common.py, leafmap/foliumap.py, leafmap/leafmap.py
This PR makes it easier to create a split-panel map with only one line of code. It supports any local or remote raster datasets. 
```python
left = 'left.tif'     # a local file path or http url
right = 'right.tif'  # a local file path or http url
m.split_map(left, right)
m
```
Several image utilities functions are also added, such as 
- `image_center()`
- `image_bounds()`
- `image_size()`
- `image_resolution()`
- `image_metadata()`
- `image_projection()`
- `image_geotransform()`
Demo:
```python
left = 'https://opendata.digitalglobe.com/events/california-fire-2020/pre-event/2018-02-16/pine-gulch-fire20/1030010076004E00.tif'
right = 'https://opendata.digitalglobe.com/events/california-fire-2020/post-event/2020-08-14/pine- …
```
=> Improve support for creating split-panel map

leafmap/common.py, leafmap/foliumap.py, leafmap/leafmap.py, leafmap/plotlymap.py
This PR improves the default `rescale` parameter for multi-band images, i.e., different bands will have different rescale values rather than the same values. For example, `rescale=["164,223","130,211","99,212"]`. The documentation has also been improved. 
@philvarner
=> Improved cog rescale param and docs #284

leafmap/foliumap.py, leafmap/leafmap.py
This PR adds GeoJSON support for the `split_map()` function. Note that ipyleaflet >=0.17.0 has a [SplitControl bug](https://github.com/jupyter-widgets/ipyleaflet/issues/440). You need to downgrade ipyleaflet to v0.17.0 or older to try out this new feature. Also, the folium plotting backend does not support this feature. 
```python
import leafmap
url = 'https://raw.githubusercontent.com/telegeography/www.submarinecablemap.com/master/web/public/api/v3/cable/cable-geo.json'
callback = lambda feat: {"color": feat["properties"]["color"]}
layer = leafmap.geojson_layer(url, style_callback=callback)
m.split_map(layer, 'OpenStreetMap')
m
```
=> Added geojson support for split map #291

leafmap/common.py
This PR adds a `is_on_aws()` function to check if a notebook is running on AWS. If yes, run `os.environ['LOCALTILESERVER_CLIENT_PREFIX'] = 'proxy/{port}'` automatically so that leafmap and localtileserver can work out of the box on AWS SageMaker. 
```python
def is_on_aws():
"""Check if the current notebook is running on AWS.
Returns:
bool: True if the notebook is running on AWS.
"""
import psutil
output = psutil.Process().parent().cmdline()
on_aws = False
for item in output:
if item.endswith(".aws"):
on_aws = True
return on_aws
```
```python
import os
os.environ['LOCALTILESERVER_CLIENT_PREFIX'] = 'proxy/{port}'
```
=> Added raster support for SageMaker AWS

leafmap/common.py
GeoPandas has changed the way to read kml. The previous method stopped working. The new way is: 
https://github.com/geopandas/geopandas/issues/2481
```python
import geopandas as gpd
import fiona
fiona.drvsupport.supported_drivers['KML'] = 'rw'
df = gpd.read_file('<filename>.kml', driver='KML')
```
=> Fixed kml bug

leafmap/common.py
This PR adds `vector_area` and `image_filesize` functions for estimating the image file size covering an area. The input can be a bounding box or any vector dataset supported by geopandas.
```python
region = [-127.793, 24.287, -66.0059, 49.6676]
leafmap.image_filesize(region, cellsize=1, bands=3, dtype='uint8', unit='TB')
```
```text
67.5696 TB
```
=> Added vector_area and image_filesize functions

leafmap/foliumap.py, leafmap/leafmap.py
This PR adds a `legend_position` parameter for the `m.add_data()` function, allowing the legend position to be specified as `bottomleft`, `bottomright`, `topleft`, and `topright`. 
#305
=> Added choropleth map legend position option #305

docs/notebooks/48_lidar.ipynb, examples/batch_update.py, examples/notebooks/48_lidar.ipynb, leafmap/common.py, leafmap/foliumap.py, leafmap/kepler.py, leafmap/leafmap.py
Pyodide does not support the `requests` module. Therefore, all download file functions using requests would not work on JupyterLite. This PR adds the `download_file_lite()` functions for downloading plain text and binary files on JupyterLite. `Map.add_geojson()` should also work out of box now.
=> Added function for downloading files using pyodide

docs/notebooks/03_cog_stac.ipynb, docs/notebooks/59_create_legend.ipynb, examples/notebooks/03_cog_stac.ipynb, examples/notebooks/59_create_legend.ipynb, leafmap/bokehmap.py, leafmap/common.py, leafmap/foliumap.py, leafmap/leafmap.py, leafmap/plotlymap.py
This PR updates the TiTiler endpoint, allowing it to be specified as an environment variable, such as `os.environ("TITILER_ENDPOINT")='https://your-endpoint' `
=> Updated TiTiler endpoint

leafmap/foliumap.py, leafmap/leafmap.py, leafmap/toolbar.py, tests/test_foliumap.py, tests/test_leafmap.py
This PR adds support for rendering vector tiles. 
For ipyleaflet
```python
import leafmap
url = "https://tile.nextzen.org/tilezen/vector/v1/512/all/{z}/{x}/{y}.mvt?api_key=gCZXZglvRQa6sB2z7JzL1w"
m.add_vector_tile(url, layer_name='Vector Tile')
m
```
For folium
```python
url = "https://tile.nextzen.org/tilezen/vector/v1/512/all/{z}/{x}/{y}.mvt?api_key=gCZXZglvRQa6sB2z7JzL1w"
m.add_vector_tile(url, layer_name='Vector Tile')
m
```
Note that the ipyleaflet vector tile layer does support `opacity` or `visible` attributes. 
Also, the folium VectorGridProtobuf does not work properly with LayerControl
https://github.com/python-visualization/folium/issues/1716
=> Add support for vector tiles

leafmap/toolbar.py
```python
import os
import leafmap
os.environ['MAX_PROPS'] = '20'
m
```
=> Add support for editing an empty vector dataset interactively

leafmap/common.py
This PR adds support for visualizing local raster datasets on AWS, including SageMaker and Studio Lab.
=> Added local raster support for AWS

leafmap/foliumap.py, leafmap/leafmap.py
This PR adds support for customizing tootip for vector data, addressing https://github.com/giswqs/leafmap/discussions/365.
Customize the `fields` parameter. 
```python
data = leafmap.examples.datasets.countries_geojson
m.add_data(
data, column='POP_EST', scheme='Quantiles', cmap='Blues', legend_title='Population', fields=['NAME', 'POP_EST']
)
m
```
=> Added support for customizing tooltip 

leafmap/common.py
Adds a `query` parameter to the `download_ned()` function. The default `query` parameter value is 
`query = {"datasets": "National Elevation Dataset (NED) 1/3 arc-second", 'prodFormats': 'GeoTIFF'}`, which should return only GeoTIFF files. Update the package using `leafmap.update_package()` and restart the kernel to take effect.
```python
region = [-115.9689, 35.9758, -115.3619, 36.4721]
leafmap.download_ned(region, return_url=True)
```
```text
['https://prd-tnm.s3.amazonaws.com/StagedProducts/Elevation/13/TIFF/historical/n36w116/USGS_13_n36w116_20201210.tif',
'https://prd-tnm.s3.amazonaws.com/StagedProducts/Elevation/13/TIFF/historical/n36w116/USGS_13_n36w116_20221019.tif',
'https://prd-tnm.s3.amazonaws.com/StagedProducts/Elevation/13/TIFF/historical/n37w116/USGS_13_n37w116_20201210.tif', …
```
=> Fixed download NED bug

docs/notebooks/67_maxar_open_data.ipynb, docs/notebooks/68_openaerialmap.ipynb, docs/tutorials.md, examples/README.md, examples/notebooks/67_maxar_open_data.ipynb, examples/notebooks/68_openaerialmap.ipynb, leafmap/common.py, leafmap/foliumap.py, leafmap/leafmap.py, leafmap/stac.py, leafmap/toolbar.py, mkdocs.yml
This PR adds support for searching OpenAerialMap imagery #371 
```python
import leafmap
bbox = [-77.2078, 17.6754, -76.3014, 18.2424]
gdf = leafmap.oam_search(bbox=bbox, return_gdf=True)
m.add_gdf(gdf, layer_name='Footprints')
m
```
=> Add support for searching OpenAerialMap imagery

docs/workshops/FOSS4G_2021.ipynb, leafmap/leafmap.py, leafmap/toolbar.py, tests/test_colormaps.py
Ipyleaflet is deprecating `Map.add_layer()` and `Map.add_control()` methods. This PR updates all relevant code to `Map.add()`.
=> Deprecate ipyleaflet add_layer and add_control methods

leafmap/stac.py
By default, `Map.add_cog_layer()` adds a `rescale` parameter to a single band raster to achieve an optimal visualization. This might not be ideal for some COG files with a built-in colormap in it, such as as land cover maps. This PR adds a `default_vis` parameter to the function to force leafmap to use the built-in colormap from the data. 
Update your package using `leafmap.update_package()` and restart the kernel to take effect. This improvement will be included in the next leafmap release. 
```python
import leafmap
url = 'https://data.mundialis.de/geodata/lulc-germany/classification_2021/classification_map_germany_2021_v01_COG.tif'
m.add_cog_layer(url, name='LULC Germany 2021', default_vis=True)
m
```
=> Add default_vis option to cog_tile() function

mkdocs.yml
The large `search_index.json` file (~50 Mb) generated by `mkdocs-jupyter` makes the website unresponsive. The PR removes the mkdocs search and replace it with Google search. 
https://github.com/giswqs/geemap/issues/1437
=> Remove mkdocs search

leafmap/deck.py, leafmap/foliumap.py, leafmap/heremap.py, leafmap/kepler.py, leafmap/leafmap.py, leafmap/plotlymap.py, requirements.txt
ipywidgets v8.05 no loner requires ipykernel. It breaks some downstream packages. This PR adds `import ipykernel.ipkernel` to each module. 
https://github.com/jupyter-widgets/ipywidgets/issues/3729
=> Fix ipywidgets error

docs/changelog.md, leafmap/deck.py, leafmap/foliumap.py, leafmap/heremap.py, leafmap/kepler.py, leafmap/leafmap.py, leafmap/plotlymap.py
The ipywidgets bug has been fixed upstream. This PR remove the ipykernel import to avoid the JupyterLite import error #402
=> Remove ipykernel import

leafmap/toolbar.py
Users can set environment variables to determine which widget to show on the toolbar. 
```python
import os
import leafmap
os.environ['TIMESLIDER'] = 'FALSE'
os.environ['WHITEBOX'] = 'FALSE'
os.environ['SPLIT_MAP'] = 'FALSE'
m
```
```bash
export TIMESLIDER=FALSE
export WHITEBOX=FALSE
export SPLIT_MAP=FALSE
```
=> Set toolbar widget visibility with env variables

docs/notebooks/73_custom_stac.ipynb, docs/tutorials.md, docs/workshops/YouthMappers_2021.ipynb, examples/README.md, examples/notebooks/73_custom_stac.ipynb, leafmap/common.py, leafmap/leafmap.py, leafmap/stac.py, leafmap/toolbar.py, mkdocs.yml, requirements_docs.txt
This new feature allows users to specify a list of STAC catalogs through an environment variable, map initialization, or map attribute. 
Working in progress. The following code is just for testing. After the implementation is completed, the GUI should be accessible through the toolbar.  @abarciauskas-bgse
```python
import leafmap
from leafmap.toolbar import stac_custom_gui
catalogs = {
"MAAP": "https://stac.maap-project.org",
"Earth Search": "https://earth-search.aws.element84.com/v1",
"Planetary Computer": "https://planetarycomputer.microsoft.com/api/stac/v1",
}
setattr(m, "_STAC_CATALOGS", catalogs)
stac_custom_gui(m)
m
```
=> Add GUI for custom STAC catalogs

leafmap/toolbar.py
I just discovered that ipywidget dropdown widget behaves differently on macOS and Linux. On macOS, a dropdown widget value is automatically set to the first item of options, while on Linux, the widget value is None. This PR set the dropdown value explicitly.
=> Fix custom STAC GUI bug

leafmap/foliumap.py, leafmap/leafmap.py
This PR adds the `max_cluster_radius` parameter for the `add_points_from_xy` function.  #416 
```python
data = 'https://raw.githubusercontent.com/opengeos/leafmap/master/examples/data/us_cities.csv'
m.add_points_from_xy(data, x="longitude", y="latitude", max_cluster_radius=80)
m
```
```python
data = 'https://raw.githubusercontent.com/opengeos/leafmap/master/examples/data/us_cities.csv'
m.add_points_from_xy(data, x="longitude", y="latitude", max_cluster_radius=50)
m
```
=> Add marker cluster radius option

leafmap/common.py, leafmap/stac.py
This PR improves the `stac_client` function by adding additional parameters such as `request_modifier` and `stac_io` that are supported by the `pystac.Client.open()` method. 
https://pystac-client.readthedocs.io/en/stable/api.html#pystac_client.Client.open
AWS SigV4
https://github.com/stac-utils/pystac-client/blob/main/docs/tutorials/authentication.md#aws-sigv4
=> Add request_modifier param to stac_client

.github/workflows/docs-build.yml, leafmap/common.py
This PR adds the `bbox` parameter for the `create_timelapse` function, allowing users to specify a bounding box in the format of `[xmin, ymin, xmax, ymax]`
=> Add bbox parameter for create_timelapse function

.github/workflows/docs-build.yml, leafmap/common.py
This PR fixes the bug when adding tile layers to ArcGIS Pro when there is no active map #433
=> Fix ArcGIS add layer bug

leafmap/common.py
The simplified code may be slightly more readable and concise.
The performance difference between the two approaches is likely to be minimal.
=> sorted function instead of if statements

leafmap/foliumap.py
This PR adds the folium `Map.add_markers_from_xy()` method for supporting custom marker shape and color.
```python
csv = 'https://github.com/opengeos/data/raw/main/world/world_cities.csv'
m.add_markers_from_xy(csv, icon_shape='circle-dot', border_width=3, border_color='#0000ff')
m
```
```python
m.add_markers_from_xy(csv, icon_shape='rectangle-dot', border_width=3, border_color='#ff0000')
```
=> Add folium add_markers_from_xy method

leafmap/common.py, leafmap/leafmap.py, leafmap/toolbar.py, tests/test_colormaps.py
Leafmap uses ipywidget's Output widget heavily to display text and plots. It appears that Output widget behaves different in different environments, causing issues such as  disappearing maps in ArcGIS Pro. 
The problematic way:
```python
import ipywidgets as widgets
output = widgets.Output()
with output:
print('Hello World')
output
```
```python
output.clear_output()
```
The recommended way:
```python
import ipywidgets as widgets
output = widgets.Output()
output.append_stdout('Hello World')
output
```
```python
output.outputs = ()
```
Relevant issues:
- https://github.com/jupyter-widgets/ipywidgets/issues/3260
- https://github.com/jupyter-widgets/ipywidgets/issues/2584
- https://github.com/jupyter-widgets/ipywidgets/pull/3261
- https://github.com/widgetti/solara/issues/127
- …
=> Fix ipywidget Output widget bug

leafmap/stac.py
This PR fixes the stac tile layer bug by add `asset_as_band=True` when `expression` use. #448
=> Fix stac layer expression bug

leafmap/foliumap.py
=> Add zoom_to_layer param for folium add_cog_layer

Dockerfile, leafmap/foliumap.py
Fix #509
Pin `jsonschema==4.18.0`
=> Fix docker image error

leafmap/common.py
_lon_ was hard-coded as a variable name in the shifting logic, and was ignoring the variable being passed to the function. This fixes the bug.
=> Fix netcdf_to_tif to correctly shift longitude with custom variable name

docs/notebooks/33_image_overlay.ipynb, docs/notebooks/70_zonal_stats.ipynb, docs/notebooks/72_timelapse.ipynb, docs/notebooks/76_image_comparison.ipynb, docs/notebooks/77_split_raster.ipynb, docs/workshops/EarthCube_2023.ipynb, examples/notebooks/33_image_overlay.ipynb, examples/notebooks/70_zonal_stats.ipynb, examples/notebooks/72_timelapse.ipynb, examples/notebooks/76_image_comparison.ipynb, examples/notebooks/77_split_raster.ipynb, examples/workshops/EarthCube_2023.ipynb
changed `opengeos.github.io` to `open.gishub.org`
=> Update opengeos url

.gitignore, docs/changelog.md, docs/changelog_update.md, docs/changelog_update.py, leafmap/basemaps.py
Add a script for automatically converting GitHub release notes to changelog for mkdocs
=> Add changelog script

docs/notebooks/81_buildings.ipynb, docs/tutorials.md, examples/README.md, examples/notebooks/81_buildings.ipynb, leafmap/common.py
Download Google Open Buildings
=> Add support for downloading google buildings

leafmap/foliumap.py, leafmap/leafmap.py
```python
import leafmap
m.add_ee_layer('USGS/SRTMGL1_003', 'DEM')
m
```
=> Add add_ee_layer function

docs/notebooks/82_pmtiles.ipynb, examples/notebooks/82_pmtiles.ipynb, leafmap/common.py, leafmap/foliumap.py, requirements_dev.txt
Add functions for converting vector data to mbtiles and pmtiles; get pmtiles header and metadata, such as layer names, center, bounds, etc. 
```python
import leafmap
url = "https://storage.googleapis.com/ahp-research/overture/pmtiles/overture.pmtiles"
metadata = leafmap.pmtiles_metadata(url)
print(metadata['layer_names'])
print(metadata['bounds'])
print(metadata['center'])
```
=> Add support for PMTiles

leafmap/leafmap.py
This feature is not officially supported by ipyleaflet yet. Wait until this PR https://github.com/jupyter-widgets/ipyleaflet/pull/1138 is merged. For now, install it with the following command:
```bash
pip install git+https://github.com/giswqs/ipyleaflet.git@pmtiles
```
```python
from ipyleaflet import Map, basemaps, PMTilesLayer
m = Map(center=[52.963529, 4.776306], zoom=7, basemap=basemaps.CartoDB.DarkMatter, scroll_wheel_zoom=True)
m.layout.height = '600px'
vl = PMTilesLayer(url="https://storage.googleapis.com/ahp-research/overture/pmtiles/overture.pmtiles", 
style = {
"layers": [
{
"id": "admins",
"source": "example_source",
"source-layer": "admins",
"type": "fill",
"paint": {"fill-color": "#BDD3C7", "fill-opacity": 0.1},
},
{
"id": "buildings",
"source": "example_source", …
```
=> Add ipyleaflet support for PMTiles

leafmap/deckgl.py
This PR adds `to_streamlit` method for the lonboard backend. It appears that the html file generated by lonboard does not work properly with streamlit. No solution yet. Will look into this in the future.
=> Add streamlit support for lonboard

docs/plot.md, leafmap/deckgl.py, leafmap/foliumap.py, leafmap/leafmap.py, leafmap/plot.py, mkdocs.yml, requirements.txt
Add bar_chart, pie_chart, line_chart, histogram, etc.
=> Add plot functions

leafmap/foliumap.py, tests/test_foliumap.py
I couldnt find any method to add a legend to a custom WMS legend into a Map. image_overlay is set to bounds, and builtin legends don't allow custom legends.
Perhaps I missed something, but if not, this might be a nice start for a add_wms_legend method
=> Add wms legend method to Map class

leafmap/__init__.py, leafmap/common.py, leafmap/foliumap.py
This PR adds the `tooltip` option for PMTiles. Fix #571 
Adapted from https://github.com/jtmiclat/folium-pmtiles/pull/13. Credits to jtmiclat.
```python
import leafmap 
style = {
"version": 8,
"sources": {
"example_source": {
"type": "vector",
"url": "pmtiles://" + url,
"attribution": 'PMTiles',
}
},
"layers": [
{
"id": "buildings",
"source": "example_source",
"source-layer": "landuse",
"type": "fill",
"paint": {"fill-color": "steelblue"},
},
{
"id": "roads",
"source": "example_source",
"source-layer": "roads",
"type": "line",
"paint": {"line-color": "black"},
},
],
}
leafmap.view_pmtiles(
url, 
name='PMTiles', 
style=style, 
zoom_to_layer=True, 
tooltip=True, 
map_args={'height': 600}
)
```
@jinha This might be of interest to you.
=> Add tooltip for PMTiles

leafmap/foliumap.py, leafmap/leafmap.py
Fix #627
```python
m = leafmap.Map(center=[40, -100], zoom=4)
data = "https://raw.githubusercontent.com/opengeos/leafmap/master/examples/data/us_cities.csv"
m.add_circle_markers_from_xy(
data, x="longitude", y="latitude", radius=10, color="blue", fill_color="black", font_size=5
)
m
```
=> Add font size option for circle marker

leafmap/foliumap.py
* allows multiple PMTilesLayer to be added/toggled via LayerControl without JS errors (protocol variable is re-declared, each layer should have a unique pane)
* allows tooltips to show after PMTilesLayer has been disabled and re-enabled via LayerControl
Below snippet is what I used for debugging/testing in Jupyter:
```python
from folium.elements import JSCSSMixin
from folium.map import Layer
from jinja2 import Template
from branca.element import MacroElement
class PMTilesMapLibreTooltipFixed(JSCSSMixin, MacroElement):
_template = Template(
"""
{% macro header(this, kwargs) %}
<style>
.maplibregl-popup {
font: 12px/20px 'Helvetica Neue', Arial, Helvetica, sans-serif;
z-index: 651;
}
.feature-row{
margin-bottom: 0.5em;
&:not(:last-of-type) {
border-bottom: 1px solid black;
}
}
</style>
{% …
```
=> fixed namespace and event handling issue with PMTilesLayer, PMTilesMapLibreTooltip

docs/notebooks/88_nasa_earth_data.ipynb, docs/tutorials.md, examples/README.md, examples/notebooks/88_nasa_earth_data.ipynb, leafmap/common.py, mkdocs.yml, requirements_dev.txt
This PR adds support for searching and downloading NASA Earth data with the [earthaccess](https://github.com/nsidc/earthaccess) Python package, making it easier to visualize the footprints of the data products. Visualizing the imagery is coming soon. 
@BriannaLind @betolink @mfisher87
Fix #620 
```python
results, gdf = leafmap.nasa_data_search(
short_name='GEDI_L4A_AGB_Density_V2_1_2056',
cloud_hosted=True,
bounding_box=(-73.9872, -33.7683, -34.7299, 5.2444),
temporal=("2020-07-01", "2020-07-31"),
count=-1,   # use -1 to return all datasets
return_gdf=True
)
gdf.explore()
```
=> Add support for downloading NASA Earth data

docs/notebooks/88_nasa_earth_data.ipynb, docs/notebooks/89_image_array_viz.ipynb, docs/tutorials.md, examples/README.md, examples/notebooks/88_nasa_earth_data.ipynb, examples/notebooks/89_image_array_viz.ipynb, leafmap/common.py, leafmap/leafmap.py, mkdocs.yml
Add support for visualizing in-memory raster datasets, e.g., numpy.ndarray and xarray.DataArray. Fix #650.
=> Add support for visualizing in-memory raster

examples/notebooks/87_actinia.ipynb
Simplified installation to `pip install actinia_python_client` after recent release on https://pypi.org/project/actinia-python-client/
=> 87_actinia.ipynb: simplify installation of actinia_python_client

examples/notebooks/52_netcdf.ipynb, leafmap/leafmap.py
This commit extends the functionality of the LeafMap module in leafmap.py, specifically focusing on the 'add_velocity' method. The primary enhancement is the introduction of the parameter, 'color_scale,' which allows users to pass a custom list of colors to be used for visualizing velocity vectors on the map.
The list was tested for RGB, HEX, and Color Names.
An example case for color_scale has been updated in the 52_netcdf.ipynb file.
=> Modified add_velocity in leafmap.py to support custom color list

docs/notebooks/89_image_array_viz.ipynb, examples/notebooks/89_image_array_viz.ipynb, leafmap/common.py
Fix #659
Creating in-memory raster dataset from numpy array or xarray by specifying metadata such as cellsize, crs, and transform. 
```python
transform = (30.0, 0.0, -13651650.0, 0.0, -30.0, 4576290.0)
ndvi_image = leafmap.array_to_image(ndvi, cellsize=30, crs="EPSG:3857", transform=transform)
```
=> Fix array_to_image bug

leafmap/foliumap.py, leafmap/leafmap.py
This PR fixes the `add_raster` colormap bug reported in #673. 
A related nodata issue is reported in https://github.com/banesullivan/localtileserver/issues/197
=> Fix add raster colormap bug

leafmap/foliumap.py, leafmap/leafmap.py
This PR adds xarray and numpy array support for the `add_raster` method. Fix #676 @lopezvoliver
```python
m.add_raster(ndvi, colormap="Greens", layer_name="NDVI", array_args={"source": satellite})
m
```
=> Add xarray support for add_raster

examples/notebooks/89_image_array_viz.ipynb, leafmap/common.py
This PR makes `array_to_memory_file` check if the array has a [rio accessor](https://corteva.github.io/rioxarray/html/rioxarray.html#rioxarray-rio-accessors), and retrieve `crs` and `transform` from it.  
This makes it possible to use `add_raster` with an xarray.DataArray without having to provide the `source` keyword argument using `array_args`. 
This is demonstrated in the updated `89_image_array_viz.ipynb` notebook:
```python
m.add_raster(masked_array, colormap="coolwarm", layer_name="Classified DEM")
```
(No need for the `image = leafmap.array_to_image(masked_array, source=dem)` step)
=> Get crs and transform from xarray rio accessor in `array_to_memory_file`

leafmap/common.py, leafmap/deckgl.py
This PR fixes the bug when trying to automatically zoom to the lonboard layer. `Map._initial_view_state` only accepts EPSG:4326 coordinates. When the GeoDataFrame is not in a projection other than EPSG:4326, the map will not render. In this case, we need to convert the centroid coordinates to EPSG:4326.
=> Fix lonboard zoom to layer bug

leafmap/foliumap.py
Adds the possibility to send `options` for the `folium.plugins.VectorGridProtobuf` directly as a string, so that a JS function may be used for conditional styling (e.g., see the [second example here](https://github.com/iwpnd/folium-vectorgrid))
Here's an example with the normal `styles`:
Here's an example with conditional styling:
where `options` was defined as a string as follows:
options='''{
"vectorTileLayerStyles": {
"myLayer": function(f) {
var color = "#86340c"; 
if (f.ET >= 250) {
color = "#c49e0d";
}
if (f.ET >= 500) {
color = "#f3fe34";
}
if (f.ET >= 750) {
color = "#aefeae";
}
if (f.ET >= 1000) {
color = "#11f9fd";
}
if (f.ET >= 1250) {
color = "#698afc";
}
if (f.ET >= 1500) {
color = "#5813fc";
}
return {
fillOpacity: 1,
fillColor: color,
fill: true,
weight: 1,
color: "white", …
=> Allow to send options directly as str

leafmap/common.py
This PR adds functions for downloading and extracting multi-part archives. This can be useful downloading deep learning pre-trained models (>2GB) from GitHub. Use the following command to create a multi-part archive and upload to GitHub as assets for releases. 
```bash
zip -s 10m sam_hq_vit_tiny.zip sam_hq_vit_tiny.pth
```
```python
import leafmap
files = ["sam_hq_vit_tiny.zip", "sam_hq_vit_tiny.z01", "sam_hq_vit_tiny.z02", "sam_hq_vit_tiny.z03"]
base_url = "https://github.com/opengeos/datasets/releases/download/models/"
urls = [base_url + f for f in files]
leafmap.download_files(urls, out_dir="models", multi_part=True)
```
=> Add functions for extracting multi-part archive

leafmap/foliumap.py, leafmap/leafmap.py
This PR adds tile layer params to the split map so that it can supports params such as `opacity`
```python
import leafmap
url = "https://open.gishub.org/data/raster/srtm90.tif"
m = leafmap.Map(center=[37.6, -119], zoom=9)
m.split_map(
url,
url,
left_args={"layer_name": "DEM", "colormap_name": "terrain", "opacity": 0.7},
right_args={"layer_name": "Classified DEM", "colormap_name": "coolwarm", "opacity": 0.5}
)
m
```
=> Add tile layer params for split map

leafmap/stac.py, leafmap/toolbar.py
=> Fix custom stac bug

docs/maplibregl.md, leafmap/maplibregl.py, mkdocs.yml, requirements.txt, requirements_dev.txt
```python
from maplibre.sources import GeoJSONSource
m = leafmap.Map(center=[49.24658, -123.1256], zoom=12, height="600px")
vancouver_blocks = GeoJSONSource(
data="https://raw.githubusercontent.com/visgl/deck.gl-data/master/examples/geojson/vancouver-blocks.json",
)
layer = Layer(
type=LayerType.LINE,
source=vancouver_blocks,
paint={"line-color": "white"},
)
m.add_layer(layer)
m
```
=> Add maplibregl module

leafmap/deck.py
This PR fixes the pydeck basemap issue reported in https://github.com/opengeos/leafmap/issues/753. Somehow the pydeck_myTileLayer resourceUri stopped working. Updating the URL solves the issue. 
https://github.com/agressin/pydeck_myTileLayer
=> Fix pydeck basemap issue

docs/notebooks/29_pydeck.ipynb, examples/notebooks/29_pydeck.ipynb, leafmap/deck.py
This PR fixes the issue reported in #754.  @cboettig
By default, the `Map.add_vector()` function uses the `GeoJsonLayer` layer type, but it can be changed to other layer types, such as `ColumnLayer`. Users can also construct a `pydeck.Layer` object and then use `Map.add_layer()` to add it to the map. 
```python
import leafmap.deck as leafmap
import geopandas as gpd
m = leafmap.Map(center=(40, -100), zoom=3)
DATA_URL = 'https://data.source.coop/cboettig/conservation-policy/Inflation_Reduction_Act_Projects.geojson'
gdf = gpd.read_file(DATA_URL)
m.add_vector(gdf,layer_type="ColumnLayer", get_position=["LONGITUDE", "LATITUDE"], get_elevation="FUNDING_NUMERIC",
get_fill_color = [256,256,0, 140],
elevation_scale=.01,
radius=10000,
pickable=True,
auto_highlight=True,)
m
```
```python
import …
```
=> Improve add_vector for the deck module

leafmap/maplibregl.py
Use the `dark-matter` style if api key is not found.
=> Fix terrain style api key bug

docs/maplibre/google_earth_engine.ipynb, docs/maplibre/overview.md, leafmap/maplibregl.py, mkdocs.yml
```python
m = leafmap.Map(center=[-100, 40], zoom=3, style="3d-terrain-background")
m.add_ee_layer(asset_id="ESA/WorldCover/v200")
m.add_legend(builtin_legend="ESA_WorldCover")
m.add_layer_control()
m
```
=> Improve support for adding GEE layers

leafmap/maplibregl.py
Add support for "100%" map height
=> Improve the MapLibre to_html method

leafmap/deckgl.py
Fix #798 
```python
import leafmap.deckgl as leafmap
from lonboard import basemap
m = leafmap.Map(height=600, basemap_style=basemap.CartoBasemap.DarkMatterNoLabels)
m
```
=> Fix lonboard map init bug

docs/maplibre/add_gif.ipynb, docs/maplibre/overview.md, leafmap/common.py, leafmap/maplibregl.py, mkdocs.yml
Add functions for executing MapLibre noetbooks automatically and generating HTML with an option for replacing the MapTiler API key, making it possible to run all leafmap MapLibre examples automatically.
=> Add functions for executing MapLibre notebook

leafmap/common.py, leafmap/maplibregl.py
Remove the random port number in the HTML generated from the `add_raster()` function to avoid being identified as changes by Git.
=> Improve MapLibre to_html function

leafmap/map_widgets.py
improvement `_get_dimension` which
- the conditional has been reversed to reduce nesting and to produce an error as soon as the orientation was wrong.
- to prevent nested indexing, use tuple unpacking `(default_width, default_height)
- to improve clarity, variable assignments have separated to ensure uniform and readability, the error message was written f-string format
=> chore: improvement _get_dimension

.github/workflows/windows.yml
There is bug with matplotlib 3.9.1 on Windows. We need to pin matplotlib==3.9.0 temporarily to fix the issue.
=> Pin matplotlib==3.9.0 for Windows CI

.github/workflows/windows.yml
The matplotlib issue has been fixed upstream. We can remove the version pin now.
=> Remove matplotlib version pin

docs/notebooks/03_cog_stac.ipynb, leafmap/stac.py
Fix #867 
```python
import leafmap
url = "https://clarkcga-aquaculture.s3.amazonaws.com/data/el_salvador/cover/El_Salvador_Landcover_2022.tif"
custom_cmap = {
"0": "#000000",
"1": "#008040",
"2": "#ff0000",
"3": "#ffff00",
"4": "#8000ff",
"5": "#8080ff",
"6": "#00ff00",
"7": "#c0c0c0",
"8": "#16002d",
"9": "#ff80ff",
"10": "#b3ffb3",
"11": "#ff8080",
"12": "#ffffbf",
"13": "#000080",
"14": "#808000",
"15": "#00ffff",
}
m.add_cog_layer(url, colormap=custom_cmap, name="El_Salvador")
legend_dict = dict(zip([int(key) for key in custom_cmap.keys()], custom_cmap.values()))
m.add_legend(title="Landcover", legend_dict=legend_dict)
m
```
=> Fix COG custom colormap bug

leafmap/common.py, leafmap/maplibregl.py
```python
import os
import leafmap
os.environ["TITILER_ENDPOINT"] = "https://tt.d2s.org"
m.add_basemap("Satellite")
ortho_url = "https://ps2.d2s.org/static/projects/afc5005d-4977-4bdd-a53a-96a3f051d312/flights/32607eae-0cd9-4c06-b4d1-a4837d237ce1/data_products/0e4c3bc2-00da-41b3-bf79-d1d1f83e4194/bb62658b-a250-46e2-8e93-081828880634.tif"
url = leafmap.d2s_tile(ortho_url)
m.add_cog_layer(url, name="Image", nodata=0)
m
```
=> Add support for d2s

leafmap/common.py, leafmap/leafmap.py
This PR adds the `convert_to_gdf()` function for creating a GeoDataFrame from a geometry column or lat/lon columns.
=> Add convert_to_gdf function

docs/maplibre/overture.ipynb, docs/maplibre/overview.md, leafmap/maplibregl.py, mkdocs.yml
```python
m = leafmap.Map(
center=[-74.0095, 40.7046], zoom=16, pitch=60, bearing=-17, style="positron"
)
m.add_basemap("OpenStreetMap.Mapnik")
m.add_basemap("Esri.WorldImagery", visible=False)
m.add_overture_3d_buildings(release="2024-07-22", template="simple")
m.add_layer_control()
m
```
[![](https://github.com/user-attachments/assets/e07986eb-cc5a-4f25-b7e0-bed480a415d3)](https://leafmap.org/maplibre/overture)
=> Add support for overture data

docs/notebooks/95_edit_vector.ipynb, docs/tutorials.md, leafmap/leafmap.py, mkdocs.yml
```python
import leafmap
m = leafmap.Map(center=[40, -100], zoom=4)
geojson_url = "https://github.com/opengeos/datasets/releases/download/us/cities.geojson"
m.edit_points(geojson_url)
m
```
https://github.com/user-attachments/assets/f8d01370-2cbb-43fe-a221-fbc092b40890
=> Add support for editing points interactively

leafmap/leafmap.py
Fixed a problem when running ```add_cog_layer``` with **custom titiler_endpoint.**
When a user run ```add_cog_layer``` with custom titiler_endpoint, the user will encounter following error message.
```
---------------------------------------------------------------------------
File ~/Desktop/workspace/leafmap/leafmap/stac.py:246, in cog_tile_vmin_vmax(url, bands, titiler_endpoint, percentile, **kwargs)
[243](https://file+.vscode-resource.vscode-cdn.net/Users/swham/Desktop/workspace/leafmap/~/Desktop/workspace/leafmap/leafmap/stac.py:243)     stats = {s: stats[s] for s in stats if s in bands}
[245](https://file+.vscode-resource.vscode-cdn.net/Users/swham/Desktop/workspace/leafmap/~/Desktop/workspace/leafmap/leafmap/stac.py:245) if percentile:
--> …
```
=> Need to add titiler_endpoint argument when calling cog_tile_vmin_vmax in add_cog_layer

leafmap/foliumap.py, leafmap/leafmap.py
Fix the bug reported in https://github.com/opengeos/leafmap/issues/119#issuecomment-2365309039
=> Fix add_geojson style callback bug

leafmap/common.py
```python
import leafmap
geotiff_file = "cog.tif"
x, y, max_value = leafmap.find_max_value_coords(geotiff_file)
print(f"Original Coordinates: (x: {x}, y: {y}), Maximum Value: {max_value}")
x, y, max_value = leafmap.find_max_value_coords(geotiff_file, dst_crs="EPSG:4326")
print(f"Reprojected Coordinates: (x: {x}, y: {y}), Maximum Value: {max_value}")
```
=> Add find_max_value_coords function

leafmap/foliumap.py, leafmap/leafmap.py
Use geopandas to read vector data and convert to GeoJSON for plotting. 
Fix #920
=> Improve add_vector methods

leafmap/foliumap.py
=> Fix folium geojson style issue

docs/notebooks/99_wetlands.ipynb, leafmap/leafmap.py, mkdocs.yml
=> Improve save_draw_features function

docs/maplibre/openfreemap.ipynb, leafmap/maplibregl.py
Use the CartoDB positron style as the default positron basemap. Rename OpenFreeMap positron style to `positron2`
Fix #936
=> Change positron style basemap for maplibre

leafmap/stac.py
Fix #940 
```python
import leafmap
url = "https://earth-search.aws.element84.com/v1/"
collection = "sentinel-2-l2a"
time_range = "2020-12-01/2020-12-31"
bbox = [-122.2751, 47.5469, -121.9613, 47.7458]
result = leafmap.stac_search(
url=url,
max_items=10,
collections=[collection],
bbox=bbox,
datetime=time_range,
query={"eo:cloud_cover": {"lt": 10}},
sortby=[{"field": "properties.eo:cloud_cover", "direction": "asc"}],
)
item = result.get_all_items()[-1]
m.add_stac_layer(item, assets=["nir", "red", "green"])
m
```
=> Improve add_stac_layer to support pystac.Item

leafmap/common.py
=> Fix read_parquet bug

leafmap/common.py, leafmap/examples/__init__.py, leafmap/leafmap.py, leafmap/map_widgets.py, leafmap/maplibregl.py, leafmap/pc.py, leafmap/plotlymap.py
pkg_resources requires `setuptools`. 
This PR replaces `pkg_resources` with `importlib.resources`
=> Remove pkg_resources

leafmap/common.py, leafmap/foliumap.py, leafmap/leafmap.py, leafmap/map_widgets.py, leafmap/maplibregl.py
```python
m.add_basemap("NLCD 2019 CONUS Land Cover")
m.add_legend(title="NLCD Land Cover Classification", builtin_legend="NLCD", shape_type="circle") # line or rectangle
m
```
=> Add support for line and circle legend items

docs/maplibre/overture.ipynb, leafmap/common.py, leafmap/maplibregl.py
Add `add_overture_buildings` method for maplibre.
```python
m = leafmap.Map(center=[-74.0095, 40.7046], zoom=16)
m.add_basemap("OpenStreetMap.Mapnik")
m.add_basemap("Esri.WorldImagery", visible=False)
m.add_overture_buildings(type="line", line_color="#ff0000", line_width=2, opacity=0.8)
m.add_layer_control()
m
```
=> Improve add_overture_buildings method

leafmap/__init__.py
[marimo](https://github.com/marimo-team/marimo) notebooks need to use `folium` instead of `ipyleaflet` as the default backend. This check would allow users to copy/paste the examples on the leamap docs without modifying the code
=> improvement: support marimo notebooks

leafmap/plotlymap.py
adding more improvement including
- error handling
- handle potential exception while loading data file
- ensure that require `latitude`, `longitude`, `z` exist in input data frame, if any these missing, it will be raise error
=> chore(plotlymap): improvement file handling

leafmap/bokehmap.py
fixing warning cause using unused variable of `e` and bare exception
=> fix(warning): unused variable `e` and bare exceptions

docs/maplibre/choropleth.ipynb, docs/maplibre/overview.md, leafmap/maplibregl.py, mkdocs.yml
Create choropleth maps with a variety of classification schemes.
[![](https://github.com/user-attachments/assets/35ca3e17-956e-4d88-9e24-7e94c9e322f8)](https://leafmap.org/maplibre/change_case_of_labels)
=> Add add_data method to maplibre

leafmap/toolbar.py
Make the footprint transparent and clear output widget after the footprints have been added to the map.
=> Improve NASA Search Data

docs/notebooks/101_nasa_opera.ipynb, docs/tutorials.md, examples/README.md, leafmap/leafmap.py, leafmap/toolbar.py, mkdocs.yml
```python
import leafmap
leafmap.nasa_data_login()
m = leafmap.Map(height="650px")
m.add("NASA_OPERA")
m
```
=> Add support for NASA OPERA data products

leafmap/stac.py
The TITILER ENDPOINT MosaicJSON URL has changed.
=> Update MosaicJSON param

leafmap/common.py
Adds a check to the `array_to_memory_file` function that verifies if the crs provided by the array (from `array.rio.crs`) is not None. 
Without it, there is no way to overwrite the crs using the keyword arguments of the `array_to_memory_file` function and as a consequence the given error message ("crs must be provided if source is not provided, such as EPSG:3857") is confusing because setting the `crs` argument has no effect.
Just for completeness, the current workaround would be to set crs before calling array_to_memory_file
```
array.rio.write_crs("EPSG:3857", inplace=True)
```
=> Fix issue if xarray/rioxarray dataset does not have a crs value

docs/notebooks/103_raster_colormap.ipynb, docs/tutorials.md, examples/README.md, leafmap/common.py, leafmap/toolbar.py, mkdocs.yml
=> Add support for raster custom colormap

leafmap/foliumap.py
See `client_args = {"cors_all": True}` in Colab. 
Fix #1021
=> Fix folium split-map cors bug

leafmap/common.py, leafmap/stac.py, requirements_dev.txt
=> Fix GeoDataFrame append error

docs/maplibre/create_vector.ipynb, docs/maplibre/mapillary.ipynb, leafmap/maplibregl.py
=> Add support for Mapillary street level imagery

leafmap/osm.py
Handle the addition of `bbox` as an argument to `osmnx.features_from_bbox` (https://github.com/gboeing/osmnx/pull/1112) in v1.9.0 and onwards:
https://github.com/gboeing/osmnx/blob/d2a88cd708a23515be882ee85a4a55e420be61f6/osmnx/features.py#L82-L103
=> Handle `osmnx.features_from_bbox` interface change

leafmap/common.py, leafmap/leafmap.py
**Changes:**
1. Adding `resolution (m)` and `zoom` to the `.tif` metadata (tags) created using `map_tiles_to_geotiff`.
2. Adding an `add_bbox` method to allow a user to add bounding boxes to leafmap map.
See Previous forked PRs for full descriptions:
* PR (1) - https://github.com/Dseal95/leafmap/pull/1 
* PR (2) - https://github.com/Dseal95/leafmap/pull/2
=> augmented .tif metadata and add_bbox() functionality

leafmap/leafmap.py
**Changes:**
1. **Current behaviour:**
If a user adds N different rasters (from different source) to a map with the same `layer_name` arg the last raster added will overwrite the previous raster layers in the `m.cog_layer_dict` even though N rasters are displayed on the map.
2. **Expected behaviour:** 
If a user adds N different rasters (from different source) to a map with the same `layer_name`, subsequent rasters added after the 1st raster will have their `layer_name` appended with a suffix to make that `layer_name` unique. This will avoid any layers being overwritten in `m.cog_layer_dict`.
**Examples:**
Raw map, created using:
```
m = leafmap.Map(center=[-22.17615, -51.253043], zoom=19, height="450px")
m.add_basemap("SATELLITE")
m.layers[-1].visible = False
m.add_raster('image.tif', …
```
=> Update  add_raster() to avoid duplicate layer names being overwritten

leafmap/maplibregl.py
Fix #1068. This allows the name to render multiple times without losing layers.
=> Add use_message_queue to MapLibre Map

leafmap/maplibregl.py
Set `MapWidget._use_message_queue = False` to allow  rendering map objects multiple times.
=> Update MapLibre message queue

leafmap/maplibregl.py
Be default, message queue is not used, which allows displaying the map multiple times in a Jupyter notebook. However, the downside is that the exported HTML does not work properly.
To export the map as HTML, use `Map(use_message_queue=True) ` during map initialization or set the `USE_MESSAGE_QUEUE` environment variable.
=> Add use_message_queue param

docs/notebooks/101_nasa_opera.ipynb, leafmap/common.py, leafmap/toolbar.py
This PR adds functionality for constructing and visualizing a spatial mosaic of OPERA product granules, while retaining the ability to view/download a single product granule. Mosaicking functionality is currently only supported for OPERA products in geotiff format (RTC/DSWx/DIST).
*Specific updates:*
- Add `opera_mosaic()` function to `common.py` to enable spatial mosaicking of individual OPERA granules (xarray.DataArray objects) into a single xarray.DataArray object.
- Reformat `nasa_opera_gui` widget in `toolbar.py` to replace `Display` button with `Display (Single)` and `Display (Mosaic)` buttons, and add new logic to enable single and mosaic visualization using `opera_mosaic().
- Update `101_nasa_opera.ipynb` to accommodate mosaicking and provide example outputs.
=> Add spatial mosaic capability for OPERA products (TIFs only)

leafmap/stac.py
It appears that a TiTiler endpoint behind a reverse proxy has some performance issues. The requests sometime take too long. Use the backup endpoint when the request takes more than 10 seconds.
=> Add backup titiler endpoint

docs/maplibre/layer_groups.ipynb, docs/maplibre/overview.md, leafmap/maplibregl.py, mkdocs.yml
```python
m.add_basemap("USGS.Imagery")
m.add_basemap("OpenTopoMap")
point_url = (
"https://github.com/opengeos/datasets/releases/download/world/world_cities.geojson"
)
m.add_geojson(point_url, name="Points")
line_url = "https://github.com/opengeos/datasets/releases/download/vector/cables.geojson"
m.add_geojson(line_url, name="Lines")
groups = {"Basemap": ["USGS.Imagery", "OpenTopoMap"], "GeoJSON": ["Points", "Lines"]}
m.add_layer_manager(label="Layer Manager", groups=groups)
m
```
https://github.com/user-attachments/assets/9e31a44b-0e56-48a6-aeb4-5799dc333831
=> Add support for layer groups

leafmap/foliumap.py
Fix #1149 
To show the draw control with the export button:
```python
m = leafmap.Map(draw_export=True)
m
```
To hide the draw control
```python
m = leafmap.Map(draw_control=False)
m
```
=> Fix folium draw control bug

leafmap/maplibregl.py
Relax style URL restrictions to support both http and https. 
This is especially useful for local development setups, e.g. running a localhost server for serving styles over http.
=> Allow loading styles via http in addition to https
