opengeos/leafmap

- leafmap/leafmap.py
This PR adds the vector tile layer support to the ipyleaflet.
Addresses: https://github.com/giswqs/leafmap/issues/24
> adding vector tile layer

- examples/notebooks/01_leafmap_intro.ipynb
> added leafmap.update_package() in the example intro-notebook

- leafmap/common.py
- leafmap/toolbar.py
- requirements.txt
- tests/test_toolbar.py
> Added open raster GUI #129

- README.md
- docs/notebooks/04_cog_mosaic.ipynb
- docs/notebooks/37_planetary_computer.ipynb
- docs/tutorials.md
- examples/README.md
- examples/notebooks/04_cog_mosaic.ipynb
- examples/notebooks/37_planetary_computer.ipynb
- leafmap/common.py
- leafmap/foliumap.py
- leafmap/leafmap.py
- mkdocs.yml
- tests/test_leafmap.py
> Added Planetary Computer STAC support

- docs/plotlymap.md
- leafmap/basemaps.py
- leafmap/common.py
- leafmap/foliumap.py
- leafmap/heremap.py
- leafmap/kepler.py
- leafmap/leafmap.py
- leafmap/plotlymap.py
- leafmap/toolbar.py
- mkdocs.yml
- requirements.txt
```python
import leafmap.plotlymap as leafmap
m.add_basemap("ROADMAP")
m
```
> Add plotly backend

- docs/notebooks/39_inspector_tool.ipynb
- docs/tutorials.md
- examples/README.md
- examples/notebooks/39_inspector_tool.ipynb
- leafmap/common.py
- leafmap/leafmap.py
- leafmap/toolbar.py
- mkdocs.yml
> Add inspector tool for getting pixel values from COG/STAC

- leafmap/kepler.py
This pull request adds kwargs width.
> Added kwargs width

- docs/notebooks/41_raster_gui.ipynb
- docs/pc.md
- examples/notebooks/41_raster_gui.ipynb
- leafmap/colormaps.py
- leafmap/common.py
- leafmap/leafmap.py
- leafmap/pc.py
- leafmap/toolbar.py
- mkdocs.yml
- requirements.txt
A GUI for loading GeoTIFF, COG, STAC, and Microsoft Planetary Computer data.
> Added raster GUI #164

- docs/notebooks/50_marker_cluster.ipynb
- docs/tutorials.md
- examples/README.md
- examples/notebooks/50_marker_cluster.ipynb
- leafmap/foliumap.py
- leafmap/leafmap.py
- mkdocs.yml
```python
import leafmap
cities = 'https://raw.githubusercontent.com/giswqs/leafmap/master/examples/data/us_cities.csv'
regions = 'https://raw.githubusercontent.com/giswqs/leafmap/master/examples/data/us_regions.geojson'
m.add_geojson(regions, layer_name='US Regions')
m.add_points_from_xy(cities, x="longitude", y="latitude", color_column='region', icon_names = ['gear', 'map', 'leaf', 'globe'], spin=True)
m
```
> Added marker icon options for marker cluster

- leafmap/common.py
- leafmap/leafmap.py
Closes #231 
This PR implements some support for netCDF files with levels and times in them. By default, it'll always take index 0 of time and index 0 of levels. It also assumes the time dimension is named "time". Maybe this is a bad assumption?
I also made it so that `add_velocity` could work too because, well, it's cool.
> Add ability to handle levels and times in netCDF files

- leafmap/__init__.py
- leafmap/deck.py
- leafmap/foliumap.py
- leafmap/heremap.py
- leafmap/kepler.py
- leafmap/leafmap.py
- leafmap/plotlymap.py
The `add_data` function for creating interactive choropleth maps now supports both folium and ipyleaflet
> Added folium support for choropleth maps #235

- docs/changelog.md
- leafmap/common.py
This PR fixes the stat stats bug reported in #245
> Fixed stac stats bug #245

- docs/tutorials.md
- examples/README.md
- leafmap/common.py
- requirements_dev.txt
Check deadlinks and redirects using the [deadlink](https://github.com/nschloe/deadlink) Python package.
```base
deadlink check *
deadlinkd replace-redirects *
```
> Fixed link redirects

- docs/notebooks/54_plot_raster.ipynb
- docs/tutorials.md
- examples/README.md
- examples/notebooks/54_plot_raster.ipynb
- leafmap/common.py
This PR adds functions for plotting elevation data in 3D.
> Added plotting raster in 3D

- docs/notebooks/54_plot_raster.ipynb
- examples/notebooks/54_plot_raster.ipynb
- leafmap/__init__.py
- leafmap/report.py
- requirements.txt
This PR adds a scooby report for debugging when users report issues.
> Added scooby report

- leafmap/common.py
- leafmap/leafmap.py
The added function can covert a GitHub URL to a direct (raw) URL to the file and be used by add data functions.
> Added github_raw_url function

- leafmap/toolbar.py
- requirements.txt
This PR pins the ipyleaflet version so that it works with Colab.
> Pin ipyleaflet version for Colab

- docs/changelog.md
- docs/notebooks/09_csv_to_points.ipynb
- docs/workshops/FOSS4G_2021.ipynb
- docs/workshops/SIGSPATIAL_2021.ipynb
- docs/workshops/YouthMappers_2021.ipynb
- examples/notebooks/09_csv_to_points.ipynb
- examples/workshops/FOSS4G_2021.ipynb
- examples/workshops/SIGSPATIAL_2021.ipynb
- examples/workshops/YouthMappers_2021.ipynb
- leafmap/common.py
- tests/test_common.py
Adds `csv_to_vector` function and rename some vector conversion functions.
> Added csv_to_vector function

- leafmap/common.py
Added `convert_lidar()` and `write_lidar()` functions.
> Added more lidar functions

- docs/changelog.md
- docs/notebooks/32_local_tile.ipynb
- docs/notebooks/42_create_cog.ipynb
- docs/notebooks/47_numpy_to_cog.ipynb
- docs/notebooks/51_clip_image.ipynb
- docs/notebooks/52_netcdf.ipynb
- examples/notebooks/32_local_tile.ipynb
- examples/notebooks/42_create_cog.ipynb
- examples/notebooks/47_numpy_to_cog.ipynb
- examples/notebooks/51_clip_image.ipynb
- examples/notebooks/52_netcdf.ipynb
- leafmap/common.py
- leafmap/foliumap.py
- leafmap/leafmap.py
- leafmap/toolbar.py
> Improved add_raster function

- docs/notebooks/55_lidar.ipynb
- docs/tutorials.md
- examples/README.md
- examples/notebooks/55_lidar.ipynb
- leafmap/common.py
- mkdocs.yml
Add tutorial for LiDAR data analysis and visualizatioin.
> Added lidar tutorial

- leafmap/common.py
This PR add the `reproject()` function for reprojecting images
> Added reproject image function

- docs/notebooks/56_download_ned.ipynb
- docs/tutorials.md
- examples/README.md
- examples/notebooks/56_download_ned.ipynb
- mkdocs.yml
This PR adds the downloading NED notebook tutorial
> Added download ned notebook tutorial

- docs/notebooks/57_national_map.ipynb
- docs/notebooks/58_bokeh.ipynb
- docs/tutorials.md
- environment.yml
- examples/README.md
- examples/notebooks/57_national_map.ipynb
- examples/notebooks/58_bokeh.ipynb
- leafmap/bokehmap.py
- leafmap/common.py
- mkdocs.yml
This PR adds `fit_bounds` params for all vector and raster functions. Bokeh map will automatically fit bounds based on input datasets.
> Add fit_bounds param for bokeh maps

- leafmap/common.py
This PR adds the `add_mask_to_image()` function for overlaying a binary mask on an image.
> Add add_mask_to_image() function

- docs/notebooks/59_create_legend.ipynb
- docs/notebooks/60_add_widget.ipynb
- docs/tutorials.md
- examples/README.md
- examples/notebooks/59_create_legend.ipynb
- examples/notebooks/60_add_widget.ipynb
- leafmap/common.py
- leafmap/foliumap.py
- leafmap/leafmap.py
- mkdocs.yml
The PR adds notebook examples for using `create_legend()`, `add_legend()`, `add_text()`, `add_image()`, `add_html()`, and `add_widget()`.
> Added create_legend and add_widget notebooks

- docs/notebooks/61_vector_to_gif.ipynb
- docs/tutorials.md
- examples/README.md
- examples/notebooks/61_vector_to_gif.ipynb
- leafmap/common.py
- mkdocs.yml
This PR adds support for creating animated GIF from vector data #263
> Added support for vector_to_gif #263

- docs/notebooks/03_cog_stac.ipynb
- docs/notebooks/62_folium_colorbar.ipynb
- docs/tutorials.md
- examples/README.md
- examples/notebooks/03_cog_stac.ipynb
- examples/notebooks/62_folium_colorbar.ipynb
- leafmap/common.py
- leafmap/foliumap.py
- leafmap/leafmap.py
- tests/test_foliumap.py
This PR adds a `add_colormap()` function for folium.
> Added colorbar support for folium

- docs/notebooks/63_arcgis.ipynb
- docs/tutorials.md
- examples/README.md
- examples/notebooks/63_arcgis.ipynb
- leafmap/common.py
- leafmap/foliumap.py
- leafmap/leafmap.py
- mkdocs.yml
This PR adds support for ArcGIS Pro.
> Added support for ArcGIS Pro

- leafmap/common.py
This PR fixed the tar file bug CVE-2007-4559 https://github.com/giswqs/leafmap/issues/349
> Fixed tar file bug CVE-2007-4559

- docs/notebooks/51_clip_image.ipynb
- examples/notebooks/04_cog_mosaic.ipynb
- examples/notebooks/51_clip_image.ipynb
This PR fixes notebook 51 docs build error
> Fixed docs build error

- docs/changelog.md
- docs/notebooks/64_stac_search.ipynb
- examples/notebooks/64_stac_search.ipynb
- leafmap/stac.py
- leafmap/toolbar.py
This PR improves the STAC browser GUI. Search results can be returned as :
- `m.stac_gdf`
- `m.stac_dict`
- `m.stac_item`
> Improved STAC browser GUI

- docs/changelog.md
- docs/notebooks/67_maxar_open_data.ipynb
- docs/tutorials.md
- examples/README.md
- examples/notebooks/67_maxar_open_data.ipynb
- leafmap/basemaps.py
- leafmap/bokehmap.py
- leafmap/colormaps.py
- leafmap/common.py
- leafmap/deck.py
- leafmap/foliumap.py
- leafmap/heremap.py
- leafmap/kepler.py
- leafmap/leafmap.py
- leafmap/plotlymap.py
- leafmap/stac.py
- leafmap/toolbar.py
- requirements_dev.txt
- tests/test_common.py
References:
- https://registry.opendata.aws/maxar-open-data/
- https://stacindex.org/catalogs/maxar-open-data-catalog-ard-format#/
- https://radiantearth.github.io/stac-browser/#/external/maxar-opendata.s3.amazonaws.com/events/catalog.json?.language=en
- https://ard.maxar.com/docs/sdk/sdk/ard-collections/
> Add support for using Maxar Open Data

- .github/workflows/py311.yml
- .github/workflows/py38.yml
- .github/workflows/ubuntu.yml
- requirements_dev.txt
CI for Python 3.8 failed due to osmnx and shapefly version mismatch. 
Reference: https://stackoverflow.com/a/75062624
> Pin osmnx version lower bound

- .gitignore
- docs/search.md
- docs/search_docs.html
- mkdocs.yml
This PR adds Google Search functionality to docs. 
Relevant issue: https://github.com/giswqs/geemap/issues/1437
> Add Google Search for docs

- .gitignore
- docs/notebooks/68_openaerialmap.ipynb
- examples/notebooks/68_openaerialmap.ipynb
- leafmap/foliumap.py
This PR fixes the `add_geojson()` style bug and improves the OpenAerialMap (OAM) notebook
> Improve OpenAerialMap (OAM) notebook example

- docs/notebooks/00_key_features.ipynb
- docs/notebooks/04_cog_mosaic.ipynb
- docs/notebooks/21_ts_inspector.ipynb
- docs/notebooks/65_sagemaker.ipynb
- examples/batch_update.py
- examples/notebooks/00_key_features.ipynb
- examples/notebooks/04_cog_mosaic.ipynb
- examples/notebooks/21_ts_inspector.ipynb
- examples/notebooks/65_sagemaker.ipynb
This PR fixes the bug reported in #379
> Updated notebooks #379

- leafmap/common.py
This PR adds the `disjoint()` function for finding out the features in a GeoDataFrame that do not intesect with any features in another GeoDataFrame.
> Added disjoint function

- docs/notebooks/70_zonal_stats.ipynb
- docs/tutorials.md
- examples/README.md
- examples/notebooks/70_zonal_stats.ipynb
- leafmap/common.py
- mkdocs.yml
- requirements_dev.txt
This PR adds `zonal_stats` function
> Add zonal stats

- .github/workflows/docs-build.yml
- .github/workflows/docs.yml
- docs/notebooks/70_zonal_stats.ipynb
- docs/notebooks/71_aws_s3.ipynb
- docs/tutorials.md
- examples/README.md
- examples/batch_update.py
- examples/check_colab.py
- examples/notebooks/70_zonal_stats.ipynb
- examples/notebooks/71_aws_s3.ipynb
- leafmap/common.py
- leafmap/foliumap.py
- leafmap/kepler.py
- leafmap/leafmap.py
- leafmap/stac.py
- leafmap/toolbar.py
- mkdocs.yml
- requirements_dev.txt
- requirements_docs.txt
This PR adds functionality for getting raster datasets from a S3 bucket and visualizing datasets on the map.
> Add support for AWS S3

- leafmap/common.py
This PR fixes GitHub Code scaning warnings. 
https://github.com/giswqs/leafmap/security/code-scanning/2
> Fixed CodeQL warnings

- leafmap/common.py
Add `add_prefix` and `out_ext` parameters.
> Improved the create_timelapse function

- docs/notebooks/74_tms_to_geotiff.ipynb
- docs/tutorials.md
- examples/README.md
- examples/notebooks/74_tms_to_geotiff.ipynb
- leafmap/common.py
- mkdocs.yml
This PR adds function for downloading map tiles from TMS and creating a GeoTIFF file. 
```python
import leafmap
bbox = [-122.5216, 37.733, -122.3661, 37.8095]
leafmap.tms_to_geotiff('osm.tif', bbox, zoom=13, source='OpenStreetMap', quiet=False)
```
> Add tms_to_geotiff function

- docs/changelog.md
- leafmap/common.py
- tests/test_foliumap.py
- tests/test_leafmap.py
Customizing crs
```python
leafmap.tms_to_geotiff('satellite.tif', bbox, zoom=13, source='Satellite', crs='epsg:5070')
```
Converting GeoTIFF to JP2
```python
leafmap.tif_to_jp2('satellite.tif', 'satellite.jp2')
```
> Added tif_to_jp2 function and fixed build errors

- .github/workflows/docs-build.yml
- docs/changelog.md
- docs/notebooks/76_image_comparison.ipynb
- docs/tutorials.md
- examples/README.md
- examples/notebooks/76_image_comparison.ipynb
- leafmap/common.py
- mkdocs.yml
```python
import leafmap
img1 = 'https://i.imgur.com/k34tq0N.jpg'
img2 = "https://i.imgur.com/hcWM5rv.jpg"
leafmap.image_comparison(
img1,
img2,
label1='Satellite Image',
label2='Image Segmentation',
starting_position=50,
out_html='image_comparison.html',
)
```
> Add image comparison with a slider

- leafmap/leafmap.py
This PR add `repeatMode` for DrawControl and `zoom_to_layer` option for adding raster layers
> Add repeat mode for draw control

- docs/heremap.md
- leafmap/toolbar.py
- mkdocs.yml
- requirements_dev.txt
This PR improves the stac GUI by allowing users to pass in additional parameters like `request_modifier`
```python
from leafmap.toolbar import stac_gui
stac_gui(m, request_modifier=lambda request: sign_request(signer, request))
```
> Improve support for stac GUI

- leafmap/basemaps.py
- leafmap/leafmap.py
- leafmap/toolbar.py
- tests/test_colormaps.py
- tests/test_foliumap.py
- tests/test_leafmap.py
This PR fixes some widgets that result in errors such as `Widget has no comm, you probably using a widget that was closed`. It should now support Solara. 
https://github.com/opengeos/solara-geospatial
> Add support for Solara web apps

- leafmap/common.py
- leafmap/leafmap.py
This PR adds several vector processing functions:
- select_largest
- coords_to_vector
- vector_set_crs
> Add vector processing functions

- docs/workshops/ICRW_2023.ipynb
- examples/workshops/ICRW_2023.ipynb
- leafmap/common.py
- mkdocs.yml
This PR adds a notebook example for hydrological analysis with leafmap and WhiteboxTools.
https://github.com/mhweber/ICRW8_Geospatial_Workshop
> Add ICRW workshop notebook

- docs/workshops/ICRW_2023.ipynb
- examples/workshops/ICRW_2023.ipynb
- leafmap/leafmap.py
- leafmap/toolbar.py
This PR adds `layer_manage_gui` and `Map.add_layer_manager`
> Add layer manager GUI

- leafmap/common.py
- leafmap/leafmap.py
Example: 
```python
html_string = '<html><body><img src="image.png"></body></html>'
m.add_html(html_string)
```
#465
> Improve add_html for supporting local image

- leafmap/common.py
> add bounds warning for numpy_to_cog

- leafmap/leafmap.py
> Fix add_gdf bug

- leafmap/leafmap.py
> Improve add_gdf error handling

- docs/notebooks/75_segment_anything.ipynb
- examples/notebooks/75_segment_anything.ipynb
> Update SAM notebook

- docs/notebooks/32_local_tile.ipynb
- examples/notebooks/32_local_tile.ipynb
- leafmap/common.py
Add support for tar.gz file unzip after download
> Improve download function for tar file unzip

- mkdocs.yml
Work in progress. 
https://book.leafmap.org
> Add book link

- leafmap/basemaps.py
- leafmap/common.py
- leafmap/leafmap.py
Some improvements
- Add NLCD 2021
- Add get_geometry_type function
- Change default map height to '500px'
- Add `add_marker_cluster` function
- Set `zoom_to_layer=False` for `add_geojson` function
> Add get_geometry_type and NLCD 2021

- .github/workflows/docs-build.yml
- .github/workflows/docs.yml
- .github/workflows/py38.yml
- .github/workflows/ubuntu.yml
- leafmap/basemaps.py
- leafmap/common.py
- leafmap/foliumap.py
- leafmap/leafmap.py
- tests/test_foliumap.py
- tests/test_leafmap.py
This PR updates the Google Maps API key requirement. Users first need to get a Google Maps API key from [https://bit.ly/3sw0THG](https://bit.ly/3sw0THG). Then, set the environment variable using `leafmap.set_api_key(<API-KEY>)`
If `GOOGLE_MAPS_API_KEY` is not detected in the environment variables, then defaults to Esri basemaps. This provides backward compability. 
Here are some senarios how the basemaps are handled:
**Senario 1:** If `GOOGLE_MAPS_API_KEY` is not detected  in the environmet variables, the OpenStreetMap will be used by default. No warning message is shown.
```python
import leafmap
Map = leafmap.Map()
Map
```
**Senario 2:** If `GOOGLE_MAPS_API_KEY` is not detected  in the environmet variables and users use `add_basemap()` to add Google Maps, a warning message will be shown …
> Add Google Maps API key requirement

- leafmap/leafmap.py
Add a close button to split map
> Improve split_map function

- leafmap/common.py
- leafmap/leafmap.py
- mkdocs.yml
- requirements_dev.txt
> Enable xarray dataset in add_raster_legacy

- leafmap/common.py
Add `array_to_image` function to save an array as a GeoTIFF.
> Add array_to_image function

- docs/notebooks/79_timeseries.ipynb
- docs/tutorials.md
- examples/README.md
- examples/notebooks/79_timeseries.ipynb
- leafmap/common.py
- leafmap/foliumap.py
- leafmap/leafmap.py
- leafmap/toolbar.py
- mkdocs.yml
- tests/test_toolbar.py
Add support for visualizing time series images interactively with a time slider
> Add images_to_tiles function

- docs/notebooks/78_read_raster.ipynb
- docs/notebooks/79_timeseries.ipynb
- docs/notebooks/80_solar.ipynb
- docs/tutorials.md
- examples/README.md
- examples/notebooks/79_timeseries.ipynb
- examples/notebooks/80_solar.ipynb
- leafmap/common.py
- leafmap/leafmap.py
- mkdocs.yml
> Add support fot Google Solar API

- leafmap/common.py
> Add session header to map tiles download

- docs/notebooks/38_plotly.ipynb
- docs/notebooks/74_map_tiles_to_geotiff.ipynb
- docs/notebooks/78_read_raster.ipynb
- docs/notebooks/79_timeseries.ipynb
- docs/notebooks/80_solar.ipynb
- docs/notebooks/81_buildings.ipynb
- docs/tutorials.md
- examples/README.md
- examples/notebooks/74_map_tiles_to_geotiff.ipynb
- examples/notebooks/78_read_raster.ipynb
- examples/notebooks/79_timeseries.ipynb
- examples/notebooks/80_solar.ipynb
- examples/notebooks/81_buildings.ipynb
- leafmap/common.py
- mkdocs.yml
https://github.com/microsoft/GlobalMLBuildingFootprints
> Add support for download MS building footprints

- leafmap/common.py
https://open-data.gishub.org/google_buildings/
> Add function for convert building csv to vector

- docs/notebooks/82_pmtiles.ipynb
- examples/notebooks/82_pmtiles.ipynb
https://apps.opengeos.org/buildings.html
> Add global buildings example

- docs/notebooks/84_read_parquet.ipynb
- docs/tutorials.md
- examples/README.md
- examples/notebooks/84_read_parquet.ipynb
- leafmap/__init__.py
- leafmap/common.py
- mkdocs.yml
- requirements.txt
> Add support for reading parquet files

- docs/notebooks/84_read_parquet.ipynb
- examples/notebooks/84_read_parquet.ipynb
> Update notebook 84

- docs/notebooks/82_pmtiles.ipynb
- examples/notebooks/82_pmtiles.ipynb
- leafmap/common.py
- leafmap/foliumap.py
- leafmap/leafmap.py
```python
import leafmap
url = "https://storage.googleapis.com/ahp-research/overture/pmtiles/overture.pmtiles"
leafmap.view_pmtiles(url)
```
> Add default style for rendering PMTiles

- leafmap/foliumap.py
> Fix basemap visibility bug

- docs/notebooks/85_gedi.ipynb
- examples/notebooks/85_gedi.ipynb
- leafmap/common.py
- mkdocs.yml
- requirements_dev.txt
Convert HDF5 to GeoDataFrame then visualize it with lonboard
> Add support for visualizing GEDI data

- leafmap/foliumap.py
> Fix folium pmtiles bug

- leafmap/common.py
> Fix PMTiles metadata bug

- leafmap/foliumap.py
> Improve folium legend position docstring

- docs/notebooks/89_image_array_viz.ipynb
- examples/notebooks/89_image_array_viz.ipynb
Add a split map example to notebooks/89_image_array_viz.ipynb
> Add split map example

- docs/notebooks/90_pixel_inspector.ipynb
- examples/notebooks/90_pixel_inspector.ipynb
- leafmap/foliumap.py
- leafmap/leafmap.py
- leafmap/stac.py
- leafmap/toolbar.py
- mkdocs.yml
This PR fixes the raster pixel inspector bug reported in #688 
The inspector supports getting pixel values from a local raster dataset, COG, or STAC item.
> Fix raster pixel inspector bug

- docs/notebooks/88_nasa_earth_data.ipynb
- examples/notebooks/88_nasa_earth_data.ipynb
> Fix notebook 88 error

- leafmap/foliumap.py
Fix the folium split map bug, making the slider draggable.
> Fix split-map bug

- leafmap/toolbar.py
This PR improves the NASA Earth Data search GUI by allowing users to draw a rectange as an area of interest.
> Improve NASA Earth Data search

- leafmap/common.py
This PR adds `client_args` to some s3 client functions
> Improve s3 functions

- .github/workflows/docs-build.yml
- .github/workflows/docs.yml
This PR fixes the date issue on the docs.
> Fix docs date issue

- leafmap/common.py
> Fix checking studio lab bug

- leafmap/common.py
> Fix AWS checking for localtileserver

- docs/notebooks/32_local_tile.ipynb
- docs/notebooks/78_read_raster.ipynb
- docs/notebooks/91_raster_viz_gui.ipynb
- docs/tutorials.md
- examples/README.md
- examples/notebooks/32_local_tile.ipynb
- examples/notebooks/78_read_raster.ipynb
- examples/notebooks/91_raster_viz_gui.ipynb
- leafmap/common.py
- leafmap/leafmap.py
- leafmap/map_widgets.py
- leafmap/stac.py
- leafmap/toolbar.py
- mkdocs.yml
This PR adds a GUI for visualizing raster layers interactively. 
https://github.com/opengeos/leafmap/assets/5016453/1dd76c64-7882-4045-b15d-1281ce35f367
> Add GUI for raster data visualization

- docs/notebooks/92_maplibre.ipynb
- docs/tutorials.md
- examples/README.md
- examples/notebooks/92_maplibre.ipynb
- leafmap/common.py
- leafmap/leafmap.py
- leafmap/maplibregl.py
- mkdocs.yml
- requirements_dev.txt
This PR improves the maplibregl module by adding more functions and documentation.
> Improve the maplibre module

- docs/notebooks/92_maplibre.ipynb
- examples/notebooks/92_maplibre.ipynb
- leafmap/maplibregl.py
```python
m
m.add_basemap()
```
> Add basemap widget

- docs/notebooks/93_maplibre_pmtiles.ipynb
- docs/tutorials.md
- examples/README.md
- examples/notebooks/93_maplibre_pmtiles.ipynb
- leafmap/maplibregl.py
- mkdocs.yml
> Add support for MapLibre PMTiles

- leafmap/maplibregl.py
https://github.com/opengeos/leafmap/assets/5016453/72d78174-362a-44a6-9e44-18d86c99086a
> Add color picker for changing layer color interactively

- docs/maplibre/3d_buildings.ipynb
- docs/maplibre/3d_indoor_mapping.ipynb
- docs/maplibre/3d_terrain.ipynb
- docs/maplibre/_template.ipynb
- docs/maplibre/add_image.ipynb
- docs/maplibre/add_image_generated.ipynb
- docs/maplibre/add_marker.ipynb
- docs/maplibre/add_video.ipynb
- docs/maplibre/deckgl_layer.ipynb
- docs/maplibre/fit_bounds.ipynb
- docs/maplibre/fly_to.ipynb
- docs/maplibre/fly_to_options.ipynb
- docs/maplibre/fullscreen.ipynb
- docs/maplibre/geojson_line.ipynb
- docs/maplibre/satellite_map.ipynb
- docs/maplibre/vector_tile.ipynb
- docs/maplibre/wms_source.ipynb
- docs/notebooks/92_maplibre.ipynb
- docs/notebooks/93_maplibre_pmtiles.ipynb
- examples/notebooks/92_maplibre.ipynb
- examples/notebooks/93_maplibre_pmtiles.ipynb
- leafmap/maplibregl.py
Use the MapLibre center coordinates convention: `[lon, lat]`. This is would be different from other leafmap mapping backends.
> Change MapLibre center from lat_lon to lon_lat

- docs/maplibre/3d_terrain.ipynb
- docs/maplibre/live_update_feature.ipynb
- docs/maplibre/overview.md
- leafmap/maplibregl.py
https://github.com/opengeos/leafmap/assets/5016453/82f1c359-d6a9-41df-89b8-4da07e7d2cfa
> Add 3d terrain style

- .gitignore
- docs/maplibre/cloud_optimized_geotiff.ipynb
- docs/maplibre/local_raster.ipynb
- docs/maplibre/overview.md
- docs/maplibre/stac.ipynb
- mkdocs.yml
Visualize Cloud Optimized GeoTIFF (COG) files with TiTiler.
[![](https://i.imgur.com/t3nX3vj.png)](https://leafmap.org/maplibre/cloud_optimized_geotiff)
> Add COG and STAC examples for MapLibre

- leafmap/maplibregl.py
> Fix MapLibre style bug

- leafmap/maplibregl.py
- requirements_dev.txt
- setup.py
> Add a Container class

- docs/maplibre/custom_marker.ipynb
- docs/maplibre/geopandas.ipynb
- docs/maplibre/overview.md
- leafmap/maplibregl.py
- mkdocs.yml
Use the icon-image property to change the icon image of a marker.
[![](https://i.imgur.com/yEVKJlA.png)](https://leafmap.org/maplibre/custom_marker)
> Add add_source function and custom marker notebook

- leafmap/common.py
- leafmap/maplibregl.py
Add functions for uploading assets to a GitHub release using GitHub API
> Add GitHub API functions

- leafmap/common.py
Add `image_to_geotiff()` function for saving a rasterio image in the memory to geotiff
> Add image_to_geotiff function

- leafmap/maplibregl.py
- leafmap/stac.py
> Fix MapLibre to_html bug

- docs/maplibre/3d_buildings.ipynb
- docs/maplibre/add_3d_buildings.ipynb
- docs/maplibre/maptiler_styles.ipynb
- docs/maplibre/overview.md
- leafmap/maplibregl.py
- mkdocs.yml
Makes it easier to use MapTiler styles. 
Add 3D buildings and GIF animations to the map.
[![](https://i.imgur.com/qadwFXm.png)](https://leafmap.org/maplibre/3d_buildings_gif)
Use MapTiler styles to customize the look of your map.
[![](https://i.imgur.com/0CKEFBx.png)](https://leafmap.org/maplibre/maptiler_styles)
> Add MapTiler style function

- leafmap/leafmap.py
> Fix add geojson color bug

- leafmap/toolbar.py
> Improve layer manager gui

- leafmap/common.py
improving type hints for better readability code, including some improvement on function ``_is_tool`` by:
- add error handling block for scenario when `shutil.which` may throw and exception (such `FileNotFoundError`). this would necessitate modifying the return type appropriately
> chore: improving typehints

- docs/maplibre/3d_pmtiles.ipynb
- docs/maplibre/overview.md
- mkdocs.yml
Visualize polygons from a PMTiles source in 3D.
[![](https://i.imgur.com/113bGei.png)](https://leafmap.org/maplibre/3d_pmtiles)
> Add 3D PMTiles example

- leafmap/map_widgets.py
Add XARRAY support for RasterLayerEditor
> Improve support for LayerEditor

- leafmap/colormaps.py
- leafmap/common.py
- update docstring parameter on `colormaps`
- improving error handling and formatted string on `common` by
`subprocess.CalledProcessError` raised when the installation get fails, the error re-raised to indicate the failure
> chore: update docstring args, subprocess error handler

- docs/notebooks/94_mapbox.ipynb
- docs/tutorials.md
- leafmap/javascript/mapbox.js
- leafmap/mapbox.py
- leafmap/styles/mapbox.css
- mkdocs.yml
- requirements.txt
```python
import leafmap.mapbox as leafmap
m = leafmap.Map(center=[-100, 40], zoom=1.2, height="600px")
m
```
> Add support for Mapbox

- .github/workflows/ubuntu_test.yml
- .github/workflows/windows.yml
- docs/notebooks/52_netcdf.ipynb
- examples/notebooks/52_netcdf.ipynb
- leafmap/examples/datasets.txt
- tests/test_common.py
After the list of sample datasets after repo prunning
> Update the list of sample data

- .mergify.yml
update atomerge bot and adding comment in bot config to better readable configuration on future projects
> chore(update): automergebot

- leafmap/bokehmap.py
- leafmap/common.py
improvement on common and bokehmap by
- adding error handling to cover various potential issue.
- comprehensive exception handling to provide informative error message
- clear type hints for function arguments and return types
> chore(improvement): error handling and typehinting

- leafmap/pc.py
- leafmap/plotlymap.py
improvement typehinting on ``leafmap`` and ``plotly``
> chore: improvement typehinting

- leafmap/common.py
- leafmap/deckgl.py
Improve csv_to_vector function and add add_basemap function to lonboard
> Improve csv_to_vector and lonboard module

- leafmap/deckgl.py
Support loading local raster datasets with lonboard
> Add add_raster method for lonboard

- leafmap/common.py
> Improve array_to_image function

- leafmap/common.py
- leafmap/maplibregl.py
> Add support for DeckGL ArcLayer

- docs/notebooks/95_edit_vector.ipynb
- leafmap/leafmap.py
- leafmap/toolbar.py
```python
import leafmap
data = "https://github.com/opengeos/datasets/releases/download/places/nyc_buildings.geojson"
m.edit_polygons(data)
m
```
> Add support for editing vector data interactively

- leafmap/map_widgets.py
Fix the bug when changing band combinations for PACE data.
> Fix add hyperspectral data bug

- docs/notebooks/95_edit_vector.ipynb
- docs/notebooks/96_batch_edit_vector..ipynb
- docs/tutorials.md
- leafmap/leafmap.py
- mkdocs.yml
```python
import leafmap
data = 'https://github.com/opengeos/datasets/releases/download/places/nyc_buildings.geojson'
style = {"color": "#3388ff"}
hover_style = {'color': 'yellow', 'dashArray': '0', 'fillOpacity': 0.3}
highlight_style = {'color': '#3388ff', 'fillColor': 'yellow', 'weight': 3, 'fillOpacity': 0.5}
changed_style = {'color': '#3388ff', 'fillColor': 'red', 'weight': 3, 'fillOpacity': 0.3}
m.batch_edit_polygons(data, style, hover_style, highlight_style, changed_style)
m
```
https://github.com/user-attachments/assets/ade86129-e555-4309-994e-a5d42638fbc4
> Add support for selecting and editing multiple features

- docs/notebooks/97_overture_data.ipynb
- docs/tutorials.md
- examples/README.md
- leafmap/common.py
- requirements_dev.txt
> Add support for downloading overture maps data

- .github/workflows/docs-build.yml
- .github/workflows/docs.yml
- .github/workflows/installation.yml
- .github/workflows/macos.yml
- .github/workflows/py313.yml
- .github/workflows/ubuntu.yml
- .github/workflows/windows.yml
- docs/notebooks/98_watershed.ipynb
- docs/notebooks/99_wetlands.ipynb
- docs/tutorials.md
- examples/README.md
- leafmap/common.py
- leafmap/foliumap.py
- leafmap/leafmap.py
- mkdocs.yml
https://www.fws.gov/program/national-wetlands-inventory/wetlands-data
> Add support for downloading NWI wetlands

- leafmap/leafmap.py
Fix #923
Converting style from str to dict as needed
> Fix ipyleaflet style str issue

- leafmap/leafmap.py
> Fix gdf index issue

- leafmap/leafmap.py
A temporary fix for localtileserver minzoom issue
https://github.com/opengeos/segment-geospatial/issues/351
> Fix localtileserver minzoom issue

- leafmap/leafmap.py
> Fix edit polygon crs issue

- leafmap/common.py
```python
result = get_max_pixel_coords("flow_accum.tif", dst_crs="EPSG:4326")
print(f"Maximum pixel value: {result['max_value']}")
print(f"Coordinates in {result['crs']}: {result['coordinates']}")
```
> Add get_max_pixel_coords function

- docs/notebooks/84_read_parquet.ipynb
> Remove lonboard version pin

- leafmap/common.py
> Improve get_max_pixel_coords function

- requirements.txt
Fix https://github.com/opengeos/leafmap/issues/685#issuecomment-2452276474
> Remove setuptools

- docs/maplibre/fields_of_the_world.ipynb
- docs/maplibre/overview.md
- leafmap/maplibregl.py
- mkdocs.yml
> Add support for visualizing Fields of The World

- docs/maplibre/gps_trace.ipynb
- docs/maplibre/overview.md
- leafmap/common.py
- leafmap/maplibregl.py
- mkdocs.yml
```python
data = "https://github.com/opengeos/datasets/releases/download/vector/hike_gps_trace.csv"
m = leafmap.Map(style="3d-hybrid")
m.add_gps_trace(data, radius=5, add_line=True)
m.add_layer_control()
m
```
> Add add_gps_trace method for MapLibre

- leafmap/maplibregl.py
> Update the edit_gps_trace function

- docs/maplibre/add_icon.ipynb
- docs/maplibre/overview.md
- leafmap/leafmap.py
- leafmap/maplibregl.py
- mkdocs.yml
Add a directional icon to streams.
[![](https://github.com/user-attachments/assets/b4082d29-b604-4f52-a7e7-88d15d37c7fc)](https://leafmap.org/maplibre/add_icon)
> Add directional symbol to MapLibre

- .github/workflows/docs-build.yml
- .github/workflows/docs.yml
- .github/workflows/py313.yml
- .github/workflows/ubuntu.yml
- .github/workflows/windows.yml
- docs/maplibre/mapillary.ipynb
- docs/maplibre/overview.md
- leafmap/maplibregl.py
- mkdocs.yml
Visualize Mapillary vector tiles on a map.
[![image](https://github.com/user-attachments/assets/db9fac4f-4d67-4ccb-8f2d-06d665bdd521)](https://leafmap.org/maplibre/mapillary)
> Add support for visualizing Mapillary vector tiles

- docs/maplibre/mapillary.ipynb
- leafmap/common.py
- leafmap/maplibregl.py
> Add support for visualizing Mapillary images

- docs/maplibre/create_vector.ipynb
- docs/maplibre/overview.md
- leafmap/maplibregl.py
- mkdocs.yml
Create vector data interactively on a map.
> Add support for creating vector data interactively

- leafmap/common.py
> Fix NASA login error

- docs/maplibre/3d_choropleth.ipynb
- docs/maplibre/pmtiles.ipynb
- docs/notebooks/05_load_raster.ipynb
- docs/notebooks/33_image_overlay.ipynb
- docs/notebooks/42_create_cog.ipynb
- docs/notebooks/48_lidar.ipynb
- docs/notebooks/49_split_control.ipynb
- docs/notebooks/51_clip_image.ipynb
- docs/notebooks/54_plot_raster.ipynb
- docs/notebooks/55_lidar.ipynb
- docs/notebooks/58_bokeh.ipynb
- docs/notebooks/61_vector_to_gif.ipynb
- docs/notebooks/65_sagemaker.ipynb
- docs/notebooks/70_zonal_stats.ipynb
- docs/notebooks/72_timelapse.ipynb
- docs/notebooks/76_image_comparison.ipynb
- docs/notebooks/77_split_raster.ipynb
- docs/notebooks/79_timeseries.ipynb
- docs/notebooks/82_pmtiles.ipynb
- docs/notebooks/83_vector_viz.ipynb
- docs/notebooks/84_read_parquet.ipynb
- docs/notebooks/86_add_markers.ipynb
- docs/notebooks/89_image_array_viz.ipynb
- docs/notebooks/90_pixel_inspector.ipynb
- docs/notebooks/93_maplibre_pmtiles.ipynb
- docs/workshops/EarthCube_2023.ipynb
- docs/workshops/HGAC_2024.ipynb
- docs/workshops/Taiwan_2024.ipynb
- leafmap/common.py
- leafmap/leafmap.py
> Avoid localtileserver client being gabage collected

- docs/notebooks/105_vector_time_slider.ipynb
- docs/tutorials.md
- leafmap/common.py
- leafmap/leafmap.py
- leafmap/toolbar.py
- mkdocs.yml
> Add vector time slider

- docs/notebooks/105_vector_time_slider.ipynb
https://py.cafe/giswqs/vector-time-slider
> Add PyCafe web app for vector time slider

- docs/maplibre/overture.ipynb
- leafmap/common.py
- leafmap/maplibregl.py
- mkdocs.yml
The the latest release automatically. 
https://github.com/OvertureMaps/overturemaps-py/issues/8
> Add get_overture_latest_release function

- docs/download.md
- docs/maplibre/choropleth.ipynb
- docs/maplibre/overview.md
- leafmap/common.py
- leafmap/download.py
- mkdocs.yml
Add a download module for downloading data from Planetary Computer and Overture Maps.
> Add a download module

- docs/maplibre/edit_vector.ipynb
- docs/maplibre/overview.md
- leafmap/common.py
- leafmap/maplibregl.py
- mkdocs.yml
- pyproject.toml
> Add support for editing vector data

- docs/maplibre/globe_control.ipynb
- docs/maplibre/overview.md
- leafmap/common.py
- leafmap/maplibregl.py
- mkdocs.yml
- pyproject.toml
> Add globe projection for maplibre

- docs/maplibre/globe_control.ipynb
> Add GEE 3D globe example

- leafmap/maplibregl.py
Fix the bug reported in https://github.com/giswqs/geog-312/discussions/220.
> Fix add draw control bug

- leafmap/common.py
Only apply compress option to TIF and COG.
> Update output image compress option

- leafmap/leafmap.py
- mkdocs.yml
> Skip live_update_feature notebook

- docs/maplibre/add_labels.ipynb
- docs/maplibre/overview.md
- leafmap/common.py
- leafmap/maplibregl.py
- mkdocs.yml
https://github.com/user-attachments/assets/9889c92f-9cbe-4674-adf4-9d3926d42cb7
https://github.com/user-attachments/assets/eb3110f8-3f9f-4c17-97ae-e2c63697edd6
> Add MapLibre add_labels method

- docs/maplibre/layer_manager.ipynb
- docs/maplibre/overview.md
- leafmap/maplibregl.py
- mkdocs.yml
> Add sidebar widget and layer manager

- docs/maplibre/overview.md
- docs/maplibre/sidebar.ipynb
- leafmap/maplibregl.py
- leafmap/toolbar.py
- mkdocs.yml
> Add close button and slider to sidebar widget

- docs/maplibre/layer_styling.ipynb
- docs/maplibre/overview.md
- leafmap/maplibregl.py
- mkdocs.yml
> Add support for interactive layer styling

- leafmap/maplibregl.py
> Add layer manager support for background layers

- leafmap/maplibregl.py
```python
m = leafmap.Map(style="amazon-hybrid")
m
```
> Add support for Amazon map tiles

- leafmap/maplibregl.py
> Add Map.to_solara() method

- leafmap/common.py
- leafmap/leafmap.py
- leafmap/map_widgets.py
- leafmap/maplibregl.py
- leafmap/plotlymap.py
- leafmap/stac.py
- leafmap/toolbar.py
> Add STAC Search GUI for MapLibre

- leafmap/maplibregl.py
```python
m = leafmap.Map(style="dark-matter", projection="globe")
m.add_basemap("USGS.Imagery")
m
```
> Add USGS imagery basemap

- docs/maplibre/cloud_optimized_geotiff.ipynb
- docs/maplibre/stac.ipynb
- docs/notebooks/03_cog_stac.ipynb
- docs/notebooks/04_cog_mosaic.ipynb
- leafmap/bokehmap.py
- leafmap/common.py
- leafmap/foliumap.py
- leafmap/leafmap.py
- leafmap/maplibregl.py
- leafmap/plotlymap.py
- leafmap/stac.py
Update TiTiler demo endpoint to https://giswqs-titiler-endpoint.hf.space/
> Update TiTiler demo endpoint

- .github/workflows/docs-build.yml
- .github/workflows/docs.yml
- .github/workflows/py313.yml
- .github/workflows/ubuntu.yml
- .github/workflows/windows.yml
- docs/notebooks/02_using_basemaps.ipynb
- leafmap/basemaps.py
- leafmap/common.py
- leafmap/leafmap.py
- tests/test_foliumap.py
- tests/test_leafmap.py
- tests/test_toolbar.py
Set it as an environment variable `GOOGLE_MAPS_API_KEY`
> Add support for Google Maps API key

- docs/workshops/CVPR_2025.ipynb
- mkdocs.yml
This notebook is for the workshop (Computer Vision and Artificial Intelligence for Large-Scale Earth Observation Data) presented at the [IEEE / CVF Computer Vision and Pattern Recognition Conference (CVPR) ](https://cvpr.thecvf.com).
> Add CVPR workshop notebook

- leafmap/common.py
```python
bbox = [-99.192, 46.56, -99.1206, 46.6283]
gdf = get_nwi_year(bbox=bbox, return_geometry=True)
```
> Add get_nwi_year function

- leafmap/common.py
> Add convert_to_cog function

- leafmap/maplibregl.py
Fix bug when paint properties is a list
> Fix layer style GUI bug

- docs/maplibre/overview.md
- docs/maplibre/time_slider.ipynb
- leafmap/common.py
- leafmap/maplibregl.py
- mkdocs.yml
> Add time slider for visualizing time series data

- leafmap/common.py
https://maplibre.org/martin/introduction.html
```python
from leafmap.common import start_martin, stop_martin
p = start_martin(
mbtiles=["world_cities.mbtiles"],
pmtiles=["https://overturemaps-tiles-us-west-2-beta.s3.amazonaws.com/2025-04-23/buildings.pmtiles"],
port=3000
)
stop_martin(p) 
```
> Add support for rendering vector tiles using Martin

- docs/maplibre/mapillary.ipynb
- leafmap/maplibregl.py
> Add Mapillary StreetView panel

- docs/maplibre/arc_layer.ipynb
- docs/maplibre/overview.md
- mkdocs.yml
> Add arc layer notebook example

- docs/maplibre/add_deckgl_layer.ipynb
> Add H3HexagonLayer example

- leafmap/maplibregl.py
> Add floating sidebar to the map

- docs/maplibre/floating_sidebar.ipynb
- leafmap/maplibregl.py
- mkdocs.yml
> Add flaoting sidebar notebook example
